### ISSUE TITLE
Frontend: Optimistic UI

### ISSUE THREAD

**Issue by umxr** [bryceknz/sanity-translations-experiment#23]
# Description

Update the frontend to gracefully handle requests which take a while to load. Currently, our server is making a call to Open AI, this can take some time leading to the user sitting around bored. With `react-router-dom` we can optimistically render the UI so page transitions are almost instant while we wait for content to load

# Acceptance criteria

- [ ] If a user clicks on a post, the page should change and we should render a skeleton ui while we wait for content to load

**Comment by ayobamiseun** [comment]
Hi can i be part of this project.
