### ISSUE TITLE
Sanity: Default language should always come from language schema

### ISSUE THREAD

**Issue by dtaylorbrown** [bryceknz/sanity-translations-experiment#25]
At the moment we can detect the default language from the schema in `sanity.config.ts` but ideally we also need to be able to do this within the custom desk structure where we currently have:
```js
const defaultLanguage = {
  id: 'en-US', title: 'English (US)', default: true
};
```

This could possibly cause some issues if the default language were to ever change in the schema

# Acceptance criteria

- [ ] The default language should be retreived by the default langauge set in schema

**Comment by umxr** [comment]
This might be superseded by #39
