### ISSUE TITLE
Server: Translate post title when viewed as a list

### ISSUE THREAD

**Issue by bryceknz** [bryceknz/sanity-translations-experiment#36]
# Description

There is an inconsistent experience between viewing a post, and viewing the list of posts. Individual posts are translated, but the list of posts is not.

Let's update the server to translate the list of posts too.

_Note_: We may require a new prompt for this. Consider various options and report back to the team before proceeding with the implementation.

# Acceptance criteria

- [x] When viewing the list of posts, the titles should be translated.

**Comment by umxr** [comment]
during the migration to remix, this resolved itself :)
